#!/bin/bash

if [ "$(stat -c "%Y" "${APPLICATION_INST}/bin/fisheyectl.sh")" -eq "0" ]; then
  sed --in-place "s~#!/bin/sh~#!/bin/sh \n FISHEYE_INST=${APPLICATION_HOME}~" ${APPLICATION_INST}/bin/fisheyectl.sh
fi

exec "$@"